apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lost-tuna-nodejs
  janus-idp.io/tekton: lost-tuna-nodejs
  backstage.io/kubernetes-id: lost-tuna-nodejs
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: lost-tuna-nodejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
