apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lost-tuna-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lost-tuna-nodejs 
  name: lost-tuna-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lost-tuna-nodejs 
